import type { ThemeSpec } from './types';

export interface ThemePreset {
  id: string;
  name: string;
  /**
   * Everything a preset controls — `name` is excluded since that's the
   * user's own display name, and `typography` is excluded since font
   * choice is left to the user/default rather than switched per preset.
   */
  spec: Omit<ThemeSpec, 'name' | 'typography'>;
}

export const themePresets: ThemePreset[] = [
  {
    id: 'caramellatte',
    name: 'Caramellatte',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#000000' },
        secondary: { main: '#370a00' },
        error: { main: '#ff6266' },
        warning: { main: '#fcb700' },
        info: { main: '#193ab7' },
        success: { main: '#006044' },
        background: { default: '#feecd3', paper: '#fff7ed' },
        divider: 'rgba(255, 214, 167, 0.12)',
        text: { primary: 'rgba(124, 40, 8, 0.87)', secondary: 'rgba(124, 40, 8, 0.75)' },
      },
      shape: { boxRadius: 16, fieldRadius: 8, selectorRadius: 32, borderWidth: 2 },
      size: { fieldSize: 46, selectorSize: 26 },
    },
  },
  {
    id: 'coffee',
    name: 'Coffee',
    spec: {
      mode: 'dark',
      palette: {
        primary: { main: '#db924c' },
        secondary: { main: '#273e3f' },
        error: { main: '#fc9581' },
        warning: { main: '#ffd260' },
        info: { main: '#8ecac1' },
        success: { main: '#9db787' },
        background: { default: '#1e151d', paper: '#261b25' },
        divider: 'rgba(18, 10, 17, 0.14)',
        text: { primary: 'rgba(197, 159, 97, 0.87)', secondary: 'rgba(197, 159, 97, 0.72)' },
      },
      shape: { boxRadius: 16, fieldRadius: 8, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 43, selectorSize: 24 },
    },
  },
  {
    id: 'night',
    name: 'Night',
    spec: {
      mode: 'dark',
      palette: {
        primary: { main: '#3abdf7' },
        secondary: { main: '#818cf8' },
        error: { main: '#fb7085' },
        warning: { main: '#f4bf51' },
        info: { main: '#0ca5e9' },
        success: { main: '#2fd4bf' },
        background: { default: '#0c1425', paper: '#0f172a' },
        divider: 'rgba(10, 17, 32, 0.14)',
        text: { primary: 'rgba(201, 203, 208, 0.87)', secondary: 'rgba(201, 203, 208, 0.72)' },
      },
      shape: { boxRadius: 16, fieldRadius: 8, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 43, selectorSize: 24 },
    },
  },
  {
    id: 'lemonade',
    name: 'Lemonade',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#419400' },
        secondary: { main: '#bdc000' },
        error: { main: '#efc6c2' },
        warning: { main: '#d7d3b0' },
        info: { main: '#b1d9e9' },
        success: { main: '#b9dbc6' },
        background: { default: '#e1e6d9', paper: '#f8fdef' },
        divider: 'rgba(203, 207, 195, 0.12)',
        text: { primary: 'rgba(21, 22, 20, 0.87)', secondary: 'rgba(21, 22, 20, 0.75)' },
      },
      shape: { boxRadius: 16, fieldRadius: 8, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 43, selectorSize: 24 },
    },
  },
  {
    id: 'acid',
    name: 'Acid',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#ff00ff' },
        secondary: { main: '#ff6e00' },
        error: { main: '#ff0000' },
        warning: { main: '#ffe200' },
        info: { main: '#007fff' },
        success: { main: '#00ff8a' },
        background: { default: '#eeeeee', paper: '#f8f8f8' },
        divider: 'rgba(225, 225, 225, 0.12)',
        text: { primary: 'rgba(0, 0, 0, 0.87)', secondary: 'rgba(0, 0, 0, 0.75)' },
      },
      shape: { boxRadius: 16, fieldRadius: 16, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 43, selectorSize: 24 },
    },
  },
  {
    id: 'autumn',
    name: 'Autumn',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#8c0327' },
        secondary: { main: '#d85251' },
        error: { main: '#d40014' },
        warning: { main: '#e97f16' },
        info: { main: '#44adbb' },
        success: { main: '#499380' },
        background: { default: '#dbdbdb', paper: '#f1f1f1' },
        divider: 'rgba(197, 197, 197, 0.12)',
        text: { primary: 'rgba(20, 20, 20, 0.87)', secondary: 'rgba(20, 20, 20, 0.75)' },
      },
      shape: { boxRadius: 16, fieldRadius: 8, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 43, selectorSize: 24 },
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    spec: {
      mode: 'dark',
      palette: {
        primary: { main: '#ff79c6' },
        secondary: { main: '#bd93f9' },
        error: { main: '#ff5555' },
        warning: { main: '#f1fa8c' },
        info: { main: '#8be9fd' },
        success: { main: '#51fa7b' },
        background: { default: '#232530', paper: '#282a36' },
        divider: 'rgba(31, 32, 42, 0.14)',
        text: { primary: 'rgba(248, 248, 243, 0.87)', secondary: 'rgba(248, 248, 243, 0.72)' },
      },
      shape: { boxRadius: 16, fieldRadius: 8, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 43, selectorSize: 24 },
    },
  },
  {
    id: 'black',
    name: 'Black',
    spec: {
      mode: 'dark',
      palette: {
        primary: { main: '#3a3a3a' },
        secondary: { main: '#3a3a3a' },
        error: { main: '#ff0301' },
        warning: { main: '#ffff00' },
        info: { main: '#0000ff' },
        success: { main: '#028002' },
        background: { default: '#000000', paper: '#1b1b1b' },
        divider: 'rgba(20, 20, 20, 0.14)',
        text: { primary: 'rgba(214, 214, 214, 0.87)', secondary: 'rgba(214, 214, 214, 0.72)' },
      },
      shape: { boxRadius: 0, fieldRadius: 0, selectorRadius: 0, borderWidth: 1 },
      size: { fieldSize: 38, selectorSize: 18 },
    },
  },
  {
    id: 'wireframe',
    name: 'Wireframe',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#d4d4d4' },
        secondary: { main: '#d4d4d4' },
        error: { main: '#9d0410' },
        warning: { main: '#963b00' },
        info: { main: '#005889' },
        success: { main: '#006044' },
        background: { default: '#f5f5f5', paper: '#ffffff' },
        divider: 'rgba(235, 235, 235, 0.12)',
        text: { primary: 'rgba(22, 22, 22, 0.87)', secondary: 'rgba(22, 22, 22, 0.75)' },
      },
      shape: { boxRadius: 4, fieldRadius: 4, selectorRadius: 0, borderWidth: 1 },
      size: { fieldSize: 40, selectorSize: 20 },
    },
  },
  {
    id: 'fantasy',
    name: 'Fantasy',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#6d0076' },
        secondary: { main: '#0075c2' },
        error: { main: '#ff5861' },
        warning: { main: '#ffbe00' },
        info: { main: '#00b5ff' },
        success: { main: '#00a96e' },
        background: { default: '#e8e8e8', paper: '#ffffff' },
        divider: 'rgba(209, 209, 209, 0.12)',
        text: { primary: 'rgba(31, 41, 55, 0.87)', secondary: 'rgba(31, 41, 55, 0.75)' },
      },
      shape: { boxRadius: 16, fieldRadius: 8, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 43, selectorSize: 24 },
    },
  },
  {
    id: 'aqua',
    name: 'Aqua',
    spec: {
      mode: 'dark',
      palette: {
        primary: { main: '#13ecf3' },
        secondary: { main: '#966fb3' },
        error: { main: '#ff7265' },
        warning: { main: '#d97708' },
        info: { main: '#2563eb' },
        success: { main: '#18a34a' },
        background: { default: '#162455', paper: '#1a368b' },
        divider: 'rgba(9, 20, 68, 0.14)',
        text: { primary: 'rgba(184, 230, 254, 0.87)', secondary: 'rgba(184, 230, 254, 0.72)' },
      },
      shape: { boxRadius: 16, fieldRadius: 8, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 43, selectorSize: 24 },
    },
  },
  {
    id: 'garden',
    name: 'Garden',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#fe0075' },
        secondary: { main: '#8e4162' },
        error: { main: '#ff5861' },
        warning: { main: '#ffbe00' },
        info: { main: '#00b5ff' },
        success: { main: '#00a96e' },
        background: { default: '#d4d2d2', paper: '#e9e7e7' },
        divider: 'rgba(190, 189, 189, 0.12)',
        text: { primary: 'rgba(16, 15, 15, 0.87)', secondary: 'rgba(16, 15, 15, 0.75)' },
      },
      shape: { boxRadius: 16, fieldRadius: 8, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 43, selectorSize: 24 },
    },
  },
  {
    id: 'valentine',
    name: 'Valentine',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#f43098' },
        secondary: { main: '#ab44ff' },
        error: { main: '#f82834' },
        warning: { main: '#ff8904' },
        info: { main: '#51e8fb' },
        success: { main: '#5ce8b3' },
        background: { default: '#f9e4f0', paper: '#fcf2f8' },
        divider: 'rgba(249, 203, 229, 0.12)',
        text: { primary: 'rgba(197, 0, 90, 0.87)', secondary: 'rgba(197, 0, 90, 0.75)' },
      },
      shape: { boxRadius: 16, fieldRadius: 32, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 46, selectorSize: 26 },
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#ff6596' },
        secondary: { main: '#00e8ff' },
        error: { main: '#ff5861' },
        warning: { main: '#ffbe00' },
        info: { main: '#00b5ff' },
        success: { main: '#00a96e' },
        background: { default: '#f7e83a', paper: '#fff248' },
        divider: 'rgba(227, 212, 14, 0.12)',
        text: { primary: 'rgba(0, 0, 0, 0.87)', secondary: 'rgba(0, 0, 0, 0.75)' },
      },
      shape: { boxRadius: 0, fieldRadius: 0, selectorRadius: 0, borderWidth: 1 },
      size: { fieldSize: 38, selectorSize: 18 },
    },
  },
  {
    id: 'retro',
    name: 'Retro',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#ff9fa0' },
        secondary: { main: '#b7f6cd' },
        error: { main: '#ff6266' },
        warning: { main: '#f34700' },
        info: { main: '#0082ce' },
        success: { main: '#00776f' },
        background: { default: '#e4d8b4', paper: '#ece3ca' },
        divider: 'rgba(219, 202, 155, 0.12)',
        text: { primary: 'rgba(121, 50, 5, 0.87)', secondary: 'rgba(121, 50, 5, 0.75)' },
      },
      shape: { boxRadius: 8, fieldRadius: 4, selectorRadius: 4, borderWidth: 1 },
      size: { fieldSize: 41, selectorSize: 22 },
    },
  },
  {
    id: 'corporate',
    name: 'Corporate',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#0082ce' },
        secondary: { main: '#61738d' },
        error: { main: '#ff6266' },
        warning: { main: '#fdc700' },
        info: { main: '#0090b5' },
        success: { main: '#00a43b' },
        background: { default: '#e8e8e8', paper: '#ffffff' },
        divider: 'rgba(209, 209, 209, 0.12)',
        text: { primary: 'rgba(24, 26, 42, 0.87)', secondary: 'rgba(24, 26, 42, 0.75)' },
      },
      shape: { boxRadius: 4, fieldRadius: 4, selectorRadius: 4, borderWidth: 1 },
      size: { fieldSize: 40, selectorSize: 20 },
    },
  },
  {
    id: 'bumblebee',
    name: 'Bumblebee',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#fdc700' },
        secondary: { main: '#ff8904' },
        error: { main: '#ff6266' },
        warning: { main: '#fcb700' },
        info: { main: '#00bafe' },
        success: { main: '#00d390' },
        background: { default: '#f5f5f5', paper: '#ffffff' },
        divider: 'rgba(228, 228, 228, 0.12)',
        text: { primary: 'rgba(22, 22, 22, 0.87)', secondary: 'rgba(22, 22, 22, 0.75)' },
      },
      shape: { boxRadius: 16, fieldRadius: 8, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 43, selectorSize: 24 },
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    spec: {
      mode: 'dark',
      palette: {
        primary: { main: '#605dff' },
        secondary: { main: '#f43098' },
        error: { main: '#ff627d' },
        warning: { main: '#fcb700' },
        info: { main: '#00bafe' },
        success: { main: '#00d390' },
        background: { default: '#191e24', paper: '#1d232a' },
        divider: 'rgba(21, 25, 30, 0.14)',
        text: { primary: 'rgba(236, 249, 255, 0.87)', secondary: 'rgba(236, 249, 255, 0.72)' },
      },
      shape: { boxRadius: 8, fieldRadius: 4, selectorRadius: 8, borderWidth: 1 },
      size: { fieldSize: 41, selectorSize: 22 },
    },
  },
  {
    id: 'light',
    name: 'Light',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#422ad5' },
        secondary: { main: '#f43098' },
        error: { main: '#ff627d' },
        warning: { main: '#fcb700' },
        info: { main: '#00bafe' },
        success: { main: '#00d390' },
        background: { default: '#f8f8f8', paper: '#ffffff' },
        divider: 'rgba(238, 238, 238, 0.12)',
        text: { primary: 'rgba(24, 24, 27, 0.87)', secondary: 'rgba(24, 24, 27, 0.75)' },
      },
      shape: { boxRadius: 8, fieldRadius: 4, selectorRadius: 8, borderWidth: 1 },
      size: { fieldSize: 41, selectorSize: 22 },
    },
  },
  {
    id: 'silk',
    name: 'Silk',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#1c1c29' },
        secondary: { main: '#1c1c29' },
        error: { main: '#ff7878' },
        warning: { main: '#efc375' },
        info: { main: '#78c8ff' },
        success: { main: '#afd89e' },
        background: { default: '#f3ede9', paper: '#f7f5f3' },
        divider: 'rgba(226, 221, 217, 0.12)',
        text: { primary: 'rgba(75, 71, 67, 0.87)', secondary: 'rgba(75, 71, 67, 0.75)' },
      },
      shape: { boxRadius: 16, fieldRadius: 8, selectorRadius: 32, borderWidth: 2 },
      size: { fieldSize: 46, selectorSize: 26 },
    },
  },
  {
    id: 'dim',
    name: 'Dim',
    spec: {
      mode: 'dark',
      palette: {
        primary: { main: '#9fe88d' },
        secondary: { main: '#ff7d5d' },
        error: { main: '#ffae9b' },
        warning: { main: '#efd057' },
        info: { main: '#28ebff' },
        success: { main: '#62efbd' },
        background: { default: '#242933', paper: '#2a303c' },
        divider: 'rgba(32, 37, 46, 0.14)',
        text: { primary: 'rgba(178, 204, 214, 0.87)', secondary: 'rgba(178, 204, 214, 0.72)' },
      },
      shape: { boxRadius: 16, fieldRadius: 8, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 43, selectorSize: 24 },
    },
  },
  {
    id: 'winter',
    name: 'Winter',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#0069ff' },
        secondary: { main: '#463aa2' },
        error: { main: '#e58b8b' },
        warning: { main: '#efd7bc' },
        info: { main: '#94e7fb' },
        success: { main: '#81cfd1' },
        background: { default: '#f2f7fe', paper: '#ffffff' },
        divider: 'rgba(227, 233, 244, 0.12)',
        text: { primary: 'rgba(57, 78, 106, 0.87)', secondary: 'rgba(57, 78, 106, 0.75)' },
      },
      shape: { boxRadius: 16, fieldRadius: 8, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 43, selectorSize: 24 },
    },
  },
  {
    id: 'brick',
    name: 'Brick',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#9d2f3a' },
        secondary: { main: '#c6ad53' },
        error: { main: '#ba2e2c' },
        warning: { main: '#de6b12' },
        info: { main: '#236cb8' },
        success: { main: '#328536' },
        background: { default: '#faf7f7', paper: '#fdfcfc' },
        divider: 'rgba(88, 65, 67, 0.12)',
        text: { primary: 'rgba(41, 31, 32, 0.87)', secondary: 'rgba(107, 87, 89, 0.75)' },
      },
      shape: { boxRadius: 8, fieldRadius: 4, selectorRadius: 4, borderWidth: 2 },
      size: { fieldSize: 40, selectorSize: 22 },
    },
  },
  {
    id: 'clay',
    name: 'Clay',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#b75a24' },
        secondary: { main: '#abce4b' },
        error: { main: '#ba372c' },
        warning: { main: '#de7a12' },
        info: { main: '#236cb8' },
        success: { main: '#328536' },
        background: { default: '#faf8f7', paper: '#fdfcfc' },
        divider: 'rgba(88, 73, 65, 0.12)',
        text: { primary: 'rgba(41, 34, 31, 0.87)', secondary: 'rgba(107, 94, 87, 0.75)' },
      },
      shape: { boxRadius: 16, fieldRadius: 16, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 44, selectorSize: 24 },
    },
  },
  {
    id: 'olive',
    name: 'Olive',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#abab2b' },
        secondary: { main: '#4eb323' },
        error: { main: '#ba3f2c' },
        warning: { main: '#de8d12' },
        info: { main: '#2392b8' },
        success: { main: '#328536' },
        background: { default: '#fafaf7', paper: '#fdfdfc' },
        divider: 'rgba(88, 88, 65, 0.12)',
        text: { primary: 'rgba(41, 41, 31, 0.87)', secondary: 'rgba(107, 107, 87, 0.75)' },
      },
      shape: { boxRadius: 16, fieldRadius: 16, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 44, selectorSize: 26 },
    },
  },
  {
    id: 'jade',
    name: 'Jade',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#20b15f' },
        secondary: { main: '#45a7c4' },
        error: { main: '#ba3f2c' },
        warning: { main: '#de9312' },
        info: { main: '#2392b8' },
        success: { main: '#328544' },
        background: { default: '#f7faf8', paper: '#fcfdfc' },
        divider: 'rgba(65, 88, 75, 0.12)',
        text: { primary: 'rgba(31, 41, 35, 0.87)', secondary: 'rgba(87, 107, 96, 0.75)' },
      },
      shape: { boxRadius: 16, fieldRadius: 16, selectorRadius: 8, borderWidth: 1 },
      size: { fieldSize: 40, selectorSize: 22 },
    },
  },
  {
    id: 'lake',
    name: 'Lake',
    spec: {
      mode: 'dark',
      palette: {
        primary: { main: '#69b7d3' },
        secondary: { main: '#6a64d8' },
        error: { main: '#e25a5f' },
        warning: { main: '#ebba47' },
        info: { main: '#5fafdd' },
        success: { main: '#59c07a' },
        background: { default: '#12191c', paper: '#1b2427' },
        divider: 'rgba(163, 186, 194, 0.14)',
        text: { primary: 'rgba(240, 243, 245, 0.87)', secondary: 'rgba(198, 207, 210, 0.72)' },
      },
      shape: { boxRadius: 8, fieldRadius: 8, selectorRadius: 8, borderWidth: 1 },
      size: { fieldSize: 40, selectorSize: 22 },
    },
  },
  {
    id: 'violet',
    name: 'Violet',
    spec: {
      mode: 'dark',
      palette: {
        primary: { main: '#9b69d3' },
        secondary: { main: '#d3699e' },
        error: { main: '#e25a5f' },
        warning: { main: '#eb9947' },
        info: { main: '#5f9ddd' },
        success: { main: '#59c07a' },
        background: { default: '#18121c', paper: '#221b27' },
        divider: 'rgba(181, 163, 194, 0.14)',
        text: { primary: 'rgba(243, 240, 245, 0.87)', secondary: 'rgba(205, 198, 210, 0.72)' },
      },
      shape: { boxRadius: 8, fieldRadius: 4, selectorRadius: 4, borderWidth: 1 },
      size: { fieldSize: 40, selectorSize: 20 },
    },
  },
  {
    id: 'orchid',
    name: 'Orchid',
    spec: {
      mode: 'light',
      palette: {
        primary: { main: '#ab24b7' },
        secondary: { main: '#d24665' },
        error: { main: '#ba2c35' },
        warning: { main: '#de6a12' },
        info: { main: '#236cb8' },
        success: { main: '#32854b' },
        background: { default: '#faf7fa', paper: '#fdfcfd' },
        divider: 'rgba(86, 65, 88, 0.12)',
        text: { primary: 'rgba(40, 31, 41, 0.87)', secondary: 'rgba(105, 87, 107, 0.75)' },
      },
      shape: { boxRadius: 16, fieldRadius: 16, selectorRadius: 16, borderWidth: 1 },
      size: { fieldSize: 46, selectorSize: 26 },
    },
  },
  {
    id: 'berry',
    name: 'Berry',
    spec: {
      mode: 'dark',
      palette: {
        primary: { main: '#d36989' },
        secondary: { main: '#d3a269' },
        error: { main: '#e25c5a' },
        warning: { main: '#eb9947' },
        info: { main: '#5f9ddd' },
        success: { main: '#59c060' },
        background: { default: '#1c1215', paper: '#271b1f' },
        divider: 'rgba(194, 163, 172, 0.14)',
        text: { primary: 'rgba(245, 240, 241, 0.87)', secondary: 'rgba(210, 198, 202, 0.72)' },
      },
      shape: { boxRadius: 4, fieldRadius: 4, selectorRadius: 4, borderWidth: 1 },
      size: { fieldSize: 40, selectorSize: 20 },
    },
  },
];

/**
 * A preset carries palette (incl. semantic colors, background, divider,
 * text), shape, size, and mode — applying one replaces all of that outright
 * rather than merging. The user's own display `name` and current
 * `typography` both survive the switch — presets never change font choice.
 */
export function applyThemePreset(spec: ThemeSpec, preset: ThemePreset): ThemeSpec {
  return {
    ...preset.spec,
    name: spec.name,
    typography: spec.typography,
  };
}
